export enum SiteTypeIcons {
    RESIDENTIAL = 'RESIDENTIAL',
    APARTMENT = 'APARTMENT',
    COMMERCIAL = 'COMMERCIAL',
    OFFICE = 'OFFICE',
    INDUSTRIAL = 'INDUSTRIAL',
    INSTITUTIONAL = 'INSTITUTIONAL',
    RURAL = 'RURAL',
    OTHER = 'OTHER',
}