import { RoleCode } from "../typings/role-code.type";

export const ROLE_PERMISSION_MAP: Record<RoleCode, string[]> = {
    owner: [
        'users.read',
        'users.invite',
        'users.update',
        'sites.read',
        'sites.update',
        'zones.read',
        'zones.update',
        'devices.read',
        'devices.update',
        'lights.read',
        'lights.toggle',
        'lights.schedule.manage',
        'cameras.live.view',
        'cameras.recordings.view',
        'alarms.arm',
        'alarms.disarm',
        'automations.read',
        'automations.execute',
        'automations.update',
    ],
    system_admin: [
        'users.read',
        'users.invite',
        'users.update',
        'users.delete',
        'sites.read',
        'sites.update',
        'sites.delete',
        'zones.read',
        'zones.update',
        'zones.delete',
        'devices.read',
        'devices.update',
        'devices.delete',
        'lights.read',
        'lights.toggle',
        'lights.schedule.manage',
        'cameras.live.view',
        'cameras.recordings.view',
        'alarms.arm',
        'alarms.disarm',
        'automations.read',
        'automations.execute',
        'automations.update',
    ],
    admin: [
        'users.read',
        'users.invite',
        'users.update',
        'sites.read',
        'sites.update',
        'zones.read',
        'zones.update',
        'devices.read',
        'devices.update',
        'lights.read',
        'lights.toggle',
        'lights.schedule.manage',
        'cameras.live.view',
        'automations.read',
        'automations.execute',
        'automations.update',
    ],
    operator: [
        'sites.read',
        'zones.read',
        'devices.read',
        'lights.read',
        'lights.toggle',
        'lights.schedule.manage',
        'automations.read',
        'automations.execute',
    ],
    viewer: ['sites.read', 'zones.read', 'devices.read', 'lights.read', 'cameras.live.view', 'automations.read'],
    technician: ['devices.read', 'devices.update', 'devices.diagnostics.read', 'devices.firmware.update'],
    security_monitor: ['cameras.live.view', 'cameras.recordings.view', 'alarms.arm', 'alarms.disarm'],
};